#!/usr/bin/env python3
"""Two-stage relevance screening over the de-biased corpus (reviewer R1.1/R1.2/R1.4).

Stage 1 is the inclusive, platform-agnostic Boolean retrieval (executed in Scopus).
Stage 2, implemented here, is a transparent rule-based content filter applied to the
title+abstract of every retrieved record: a document is retained only if it mentions
BOTH an education-intent term AND a game-development term. This demonstrates that an
"inclusive-search-then-filter" design is available within the same reproducible
pipeline, and quantifies how many retrieved records would be flagged as likely
off-topic by such a rule (a proxy for retrieval precision).

Outputs:
    data/processed/relevance_screen.json
    source/table_relevance_screen.tex   (LaTeX fragment)
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parents[2]
DATA = ROOT / "data"
PROCESSED = DATA / "processed"

EDU_TERMS = [
    "education", "teaching", "learning", "curriculum", "student", "course",
    "classroom", "pedagog", "instruction", "training", "school", "university",
    "undergraduate", "k-12", "learner", "competenc", "skill",
]
GAMEDEV_TERMS = [
    "game development", "game design", "game programming", "game engine",
    "serious game", "game-based", "gamif", "video game", "game jam",
    "game creation", "developing games", "making games", "game-making",
]


def _pat(terms):
    return re.compile("|".join(re.escape(t) for t in terms))


def screen(df: pd.DataFrame) -> dict:
    edu_re, gd_re = _pat(EDU_TERMS), _pat(GAMEDEV_TERMS)
    title = df.get("Title", pd.Series([""] * len(df))).fillna("").astype(str)
    abstract = df.get("Abstract", pd.Series([""] * len(df))).fillna("").astype(str)
    text = (title + " " + abstract).str.lower()

    has_edu = text.str.contains(edu_re)
    has_gd = text.str.contains(gd_re)
    retained = has_edu & has_gd
    flagged = ~retained

    n = len(df)
    n_ret = int(retained.sum())
    n_flag = int(flagged.sum())
    # A few example flagged titles for manual inspection (deterministic: first by index).
    flagged_titles = [t for t in title[flagged].tolist() if t][:15]

    return {
        "n_total": n,
        "n_retained": n_ret,
        "n_flagged": n_flag,
        "retention_rate": round(n_ret / n, 4) if n else 0.0,
        "flag_rate": round(n_flag / n, 4) if n else 0.0,
        "missing_edu_term": int((~has_edu).sum()),
        "missing_gamedev_term": int((~has_gd).sum()),
        "rule": "retain iff (title+abstract) contains an education-intent term AND a "
                "game-development term",
        "flagged_examples": flagged_titles,
    }


def to_latex(res: dict) -> str:
    return (
        "% Auto-generated by relevance_screen.py\n"
        "\\begin{table}[h]\n\\centering\n"
        "\\caption{Stage-2 rule-based relevance screen over the "
        f"{res['n_total']} retrieved records. A record is retained only if its "
        "title+abstract mentions both an education-intent term and a "
        "game-development term.}\n\\label{tab:relevance-screen}\n"
        "\\begin{tabular}{@{\\extracolsep{\\fill}}lc@{}}\n\\toprule\n"
        "\\textbf{Screen outcome} & \\textbf{Documents} \\\\\n\\midrule\n"
        f"Retrieved (Stage 1, inclusive query) & {res['n_total']} \\\\\n"
        f"Retained by content rule (Stage 2) & {res['n_retained']} "
        f"({res['retention_rate']*100:.1f}\\%) \\\\\n"
        f"Flagged as likely off-topic & {res['n_flagged']} "
        f"({res['flag_rate']*100:.1f}\\%) \\\\\n"
        "\\bottomrule\n\\end{tabular}\n\\end{table}\n"
    )


def main() -> None:
    csvs = sorted(DATA.glob("scopus_export*.csv"))
    primary = next((p for p in csvs if "debiased" in p.name.lower()), csvs[0] if csvs else None)
    if primary is None:
        print("No Scopus export found", file=sys.stderr)
        sys.exit(1)
    df = pd.read_csv(primary, encoding="utf-8-sig")
    df.columns = [c.strip() for c in df.columns]
    res = screen(df)
    PROCESSED.mkdir(parents=True, exist_ok=True)
    (PROCESSED / "relevance_screen.json").write_text(
        json.dumps(res, indent=2, ensure_ascii=False), encoding="utf-8")
    (ROOT / "source" / "table_relevance_screen.tex").write_text(to_latex(res), encoding="utf-8")
    print(f"Screened {res['n_total']} records from {primary.name}: "
          f"retained {res['n_retained']} ({res['retention_rate']*100:.1f}%), "
          f"flagged {res['n_flagged']} ({res['flag_rate']*100:.1f}%)")


if __name__ == "__main__":
    main()
