#!/usr/bin/env python3
"""TikZ / pgfplots figure generators for the Array submission.

Reads JSON / CSV outputs from ``bibliometric_analyzer.run_full_analysis`` and
writes self-contained TikZ source into ``source/figures/<name>.tex``. The
manuscript ``\\input{}``s these instead of ``\\includegraphics{}``.

Each figure file is wrapped so it compiles standalone for inspection:

    pdflatex -shell-escape source/figures/F01_publication_timeline.tex
"""

from __future__ import annotations

import json
import math
from pathlib import Path
from typing import Any, Dict, List, Tuple

import networkx as nx
import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parents[2]
PROCESSED = ROOT / "data" / "processed"
FIGDIR = ROOT / "source" / "figures"
FIGDIR.mkdir(parents=True, exist_ok=True)

# ---------------------------------------------------------------------------
# Common preamble + wrappers.
# ---------------------------------------------------------------------------

# Loaded once from manuscript via \input{figures/_preamble} OR copied into each
# standalone wrapper. Defines pgfplots compat and a common Set2 colour cycle.
PREAMBLE = r"""\pgfplotsset{
  compat=newest,
  cycle list/Set2-8,
  every axis/.append style={
    label style={font=\footnotesize\sansmath},
    tick label style={font=\scriptsize\sansmath},
    legend style={font=\scriptsize, draw=black!40, inner sep=2pt},
    title style={font=\small\bfseries\sansmath},
    grid style={dashed, gray!30},
  },
}"""

STANDALONE_HEADER = r"""\documentclass[border=4pt]{standalone}
\usepackage{amsmath}
\usepackage{tikz}
\usepackage{pgfplots}
\usepackage{xcolor}
\usepackage{sansmath}
\usetikzlibrary{shapes.geometric,positioning,calc,fit,backgrounds,decorations.markings,arrows.meta}
"""

STANDALONE_FOOTER = r"""\end{document}"""


def _wrap(body: str, standalone: bool = True) -> str:
    """Emit a body-only TikZ fragment.

    The fragment is meant to be ``\\input{}``-ed from the manuscript; the
    manuscript already loads the required packages (tikz, pgfplots, sansmath).
    For standalone preview, use ``test_figure_standalone.tex`` in the
    figures directory which wraps any fragment in a ``standalone`` document.
    """
    return (
        "% Auto-generated by tikz_figures.py — do not edit by hand.\n"
        + body
        + "\n"
    )


def _emit(name: str, body: str) -> Path:
    path = FIGDIR / f"{name}.tex"
    path.write_text(_wrap(body), encoding="utf-8")
    return path


def _esc(s: str) -> str:
    """LaTeX-escape a string for use in axis labels / nodes."""
    return (str(s)
            .replace("\\", r"\textbackslash{}")
            .replace("%", r"\%")
            .replace("&", r"\&")
            .replace("$", r"\$")
            .replace("#", r"\#")
            .replace("_", r"\_")
            .replace("{", r"\{")
            .replace("}", r"\}")
            .replace("^", r"\^{}")
            .replace("~", r"\~{}"))


# ---------------------------------------------------------------------------
# F01 — Annual + cumulative production timeline.
# ---------------------------------------------------------------------------

def emit_publication_timeline(by_year: pd.DataFrame, completeness: Dict[str, Any]) -> Path:
    df = by_year.sort_values("Year").reset_index(drop=True)
    rows = "\n".join(f"  {int(r.Year)}  {int(r['count'])}" for _, r in df.iterrows())

    cum = df["count"].cumsum().tolist()
    cum_rows = "\n".join(f"  {int(y)}  {int(c)}"
                         for y, c in zip(df["Year"], cum))

    # Gompertz prediction (re-fit here for the smooth curve).
    gomp = ""
    if completeness and not math.isnan(completeness.get("gompertz_r2", float("nan"))):
        from scipy.optimize import curve_fit
        years = df["Year"].astype(float).to_numpy()
        cum_arr = np.array(cum, dtype=float)
        t = years - years.min()
        try:
            K_guess = max(cum_arr[-1] * 1.5, 100.0)
            def gompertz(x, K, b, c):
                return K * np.exp(-b * np.exp(-c * x))
            p, _ = curve_fit(gompertz, t, cum_arr,
                             p0=(K_guess, 5.0, 0.2), maxfev=20000,
                             bounds=([cum_arr[-1], 0.1, 0.01], [cum_arr[-1] * 100, 50.0, 5.0]))
            ts = np.linspace(0, t.max() + 5, 80)
            ys = gompertz(ts, *p)
            yrs_smooth = years.min() + ts
            gomp_lines = "\n".join(f"  {y:.2f}  {v:.2f}" for y, v in zip(yrs_smooth, ys))
            gomp = f"""
\\addplot[smooth, thick, draw=red!70!black]
  table[x index=0, y index=1] {{
{gomp_lines}
  }};
\\addlegendentry{{Gompertz, $R^{{2}}={completeness['gompertz_r2']:.3f}$}}"""
        except Exception:
            gomp = ""

    # Bi-logistic (two-wave) prediction overlay (Meyer 1994), re-fit for the curve.
    bilo = ""
    if completeness and not math.isnan(completeness.get("bilogistic_r2", float("nan"))):
        from scipy.optimize import curve_fit
        years = df["Year"].astype(float).to_numpy()
        cum_arr = np.array(cum, dtype=float)
        t = years - years.min()
        T = float(t.max())
        try:
            def bilogistic(x, L1, k1, t1, L2, k2, t2):
                w1 = L1 / (1.0 + np.exp(-np.clip(k1 * (x - t1), -50, 50)))
                w2 = L2 / (1.0 + np.exp(-np.clip(k2 * (x - t2), -50, 50)))
                return w1 + w2
            p, _ = curve_fit(
                bilogistic, t, cum_arr,
                p0=(cum_arr[-1] * 0.5, 0.4, T * 0.45, cum_arr[-1] * 0.5, 0.4, T * 0.85),
                maxfev=40000,
                bounds=([0, 0.01, 0, 0, 0.01, 0],
                        [cum_arr[-1] * 5, 5.0, T * 1.5, cum_arr[-1] * 5, 5.0, T * 1.5]))
            ts = np.linspace(0, t.max() + 5, 80)
            ys = bilogistic(ts, *p)
            yrs_smooth = years.min() + ts
            bilo_lines = "\n".join(f"  {y:.2f}  {v:.2f}" for y, v in zip(yrs_smooth, ys))
            best = completeness.get("best_model", "")
            star = " (AIC-preferred)" if best == "bilogistic" else ""
            bilo = f"""
\\addplot[smooth, thick, dashed, draw=violet!80!black]
  table[x index=0, y index=1] {{
{bilo_lines}
  }};
\\addlegendentry{{Bi-logistic, $R^{{2}}={completeness['bilogistic_r2']:.3f}${star}}}"""
        except Exception:
            bilo = ""

    body = f"""\\begin{{tikzpicture}}
\\begin{{axis}}[
  width=0.99\\linewidth, height=6.2cm,
  ybar, bar width=4pt,
  ymin=0, axis y line*=left,
  xlabel={{Year}}, ylabel={{Annual publications}},
  enlarge x limits=0.04,
  xmin={int(df["Year"].min())-1}, xmax={int(df["Year"].max())+1},
  legend pos=north west,
]
\\addplot+[fill=blue!50!black, draw=blue!50!black, opacity=0.85]
  table[x index=0, y index=1] {{
    Year Count
{rows}
  }};
\\addlegendentry{{Annual count}}
\\end{{axis}}

\\begin{{axis}}[
  width=0.99\\linewidth, height=6.2cm,
  axis y line*=right, axis x line=none,
  ymin=0,
  ylabel={{Cumulative publications}}, ylabel near ticks,
  legend pos=south east,
]
\\addplot+[smooth, thick, mark=*, mark size=1pt, draw=teal!70!black]
  table[x index=0, y index=1] {{
{cum_rows}
  }};
\\addlegendentry{{Cumulative}}{gomp}{bilo}
\\end{{axis}}
\\end{{tikzpicture}}"""
    return _emit("F01_publication_timeline", body)


# ---------------------------------------------------------------------------
# F03 — Top-N author keywords (horizontal bar).
# ---------------------------------------------------------------------------

def emit_top_keywords(keyword_counts: List[Tuple[str, int]], top_n: int = 15) -> Path:
    items = list(keyword_counts)[:top_n]
    items = list(reversed(items))  # bottom-up so top is on top in horizontal bar
    rows = "\n".join(f"  {i+1}  {c}  {{{_esc(k)}}}" for i, (k, c) in enumerate(items))
    yticks = ",".join(str(i + 1) for i in range(len(items)))
    yticklabels = ",".join("{" + _esc(k) + "}" for k, _ in items)

    body = f"""\\begin{{tikzpicture}}
\\begin{{axis}}[
  width=0.99\\linewidth, height=8cm,
  xbar, bar width=5pt, enlarge y limits=0.04,
  ymin=0.5, ymax={len(items) + 0.5}, xmin=0,
  xlabel={{Documents}}, ylabel={{}},
  ytick={{{yticks}}},
  yticklabels={{{yticklabels}}},
  nodes near coords, nodes near coords align={{horizontal}},
  every node near coord/.append style={{font=\\scriptsize}},
]
\\addplot+[fill=blue!55!black, draw=none]
  table[x index=1, y index=0] {{
    Y X
{rows}
  }};
\\end{{axis}}
\\end{{tikzpicture}}"""
    return _emit("F03_top_keywords", body)


# ---------------------------------------------------------------------------
# F04 — Top-N sources, Bradford zones colour-coded.
# ---------------------------------------------------------------------------

def emit_top_sources_bradford(bradford: Dict[str, Any], top_n: int = 12) -> Path:
    items: List[Tuple[str, int, int]] = []  # (name, count, zone)
    for z in bradford["zones"]:
        for src, c in z["sources"]:
            items.append((src, c, z["zone"]))
    items.sort(key=lambda x: -x[1])
    items = items[:top_n][::-1]
    yticks = ",".join(str(i + 1) for i in range(len(items)))
    yticklabels = ",".join("{" + _esc(s[:55]) + "}" for s, _, _ in items)
    zone_colour = {1: "red!70!black", 2: "orange!75!black", 3: "gray!60"}

    plot_lines = []
    for i, (s, c, z) in enumerate(items):
        plot_lines.append(
            f"\\addplot+[xbar, fill={zone_colour.get(z, 'gray!60')}, draw=none, bar width=5pt] coordinates {{({c},{i+1})}};"
        )
    plots = "\n".join(plot_lines)

    body = f"""\\begin{{tikzpicture}}
\\begin{{axis}}[
  width=0.99\\linewidth, height=8.4cm,
  xbar, enlarge y limits=0.04, ymin=0.5, ymax={len(items) + 0.5}, xmin=0,
  xlabel={{Documents}},
  ytick={{{yticks}}},
  yticklabels={{{yticklabels}}},
  nodes near coords, every node near coord/.append style={{font=\\scriptsize}},
  legend cell align=left,
]
{plots}
\\legend{{}}
\\end{{axis}}
\\node[anchor=south east, font=\\scriptsize, draw=black!30, inner sep=2pt]
  at (rel axis cs:1,1) {{Zone~1 \\textcolor{{red!70!black}}{{$\\blacksquare$}}\\quad
                        Zone~2 \\textcolor{{orange!75!black}}{{$\\blacksquare$}}\\quad
                        Zone~3 \\textcolor{{gray!60}}{{$\\blacksquare$}}}};
\\end{{tikzpicture}}"""
    return _emit("F04_top_sources_bradford", body)


# ---------------------------------------------------------------------------
# F05 — Bradford zone concentration curve (Lorenz-like).
# ---------------------------------------------------------------------------

def emit_bradford_curve(bradford: Dict[str, Any]) -> Path:
    sources_sorted: List[Tuple[str, int]] = []
    for z in bradford["zones"]:
        sources_sorted.extend(z["sources"])
    if not sources_sorted:
        sources_sorted = bradford.get("top_sources", [])
    sources_sorted = sorted(sources_sorted, key=lambda x: -x[1])
    cumulative = 0
    total = sum(c for _, c in sources_sorted)
    pts = []
    for i, (_, c) in enumerate(sources_sorted, start=1):
        cumulative += c
        pts.append((i, 100.0 * cumulative / max(total, 1)))
    rows = "\n".join(f"  {i}  {p:.2f}" for i, p in pts)

    # Zone boundaries.
    cum_z = 0
    boundaries = []
    for z in bradford["zones"]:
        cum_z += z["n_sources"]
        boundaries.append(cum_z)

    bound_lines = "\n".join(
        f"\\draw[gray!50, dashed] ({{axis cs:{b},0}}) -- ({{axis cs:{b},100}}) "
        f"node[anchor=south west, font=\\scriptsize] at ({{axis cs:{b},0}}) {{Z{i+1}}};"
        for i, b in enumerate(boundaries[:-1])
    )

    body = f"""\\begin{{tikzpicture}}
\\begin{{axis}}[
  width=0.99\\linewidth, height=6.4cm,
  xlabel={{Sources, ranked by document count}},
  ylabel={{Cumulative documents (\\%)}},
  xmin=1, xmax={len(pts)}, ymin=0, ymax=100,
  axis x line=bottom, axis y line=left,
  xmode=log, log basis x=10,
  legend pos=south east,
]
\\addplot+[smooth, thick, mark=none, draw=blue!60!black]
  table[x index=0, y index=1] {{
    rank pct
{rows}
  }};
\\addlegendentry{{Concentration curve, $k={bradford.get('multiplier_k', float('nan')):.2f}$}}
{bound_lines}
\\end{{axis}}
\\end{{tikzpicture}}"""
    return _emit("F05_bradford_curve", body)


# ---------------------------------------------------------------------------
# F06 — Top-N productive authors.
# ---------------------------------------------------------------------------

def emit_top_authors(authors: List[Tuple[str, int]], top_n: int = 12) -> Path:
    items = list(authors)[:top_n][::-1]
    yticks = ",".join(str(i + 1) for i in range(len(items)))
    yticklabels = ",".join("{" + _esc(a) + "}" for a, _ in items)
    rows = "\n".join(f"  {i+1}  {n}" for i, (_, n) in enumerate(items))
    body = f"""\\begin{{tikzpicture}}
\\begin{{axis}}[
  width=0.99\\linewidth, height=7cm,
  xbar, bar width=5pt, enlarge y limits=0.04,
  ymin=0.5, ymax={len(items) + 0.5}, xmin=0,
  xlabel={{Publications}},
  ytick={{{yticks}}}, yticklabels={{{yticklabels}}},
  nodes near coords, every node near coord/.append style={{font=\\scriptsize}},
]
\\addplot+[fill=teal!70!black, draw=none]
  table[x index=1, y index=0] {{
    Y X
{rows}
  }};
\\end{{axis}}
\\end{{tikzpicture}}"""
    return _emit("F06_top_authors", body)


# ---------------------------------------------------------------------------
# F07 — Lotka law fit (log-log).
# ---------------------------------------------------------------------------

def emit_lotka_fit(lotka: Dict[str, Any]) -> Path:
    dist = lotka.get("productivity_distribution", {})
    if not dist:
        body = "\\begin{tikzpicture}\\node{No data};\\end{tikzpicture}"
        return _emit("F07_lotka_fit", body)
    pts = sorted((int(k), int(v)) for k, v in dist.items())
    rows = "\n".join(f"  {n}  {f}" for n, f in pts)
    alpha = lotka.get("alpha", float("nan"))
    c = lotka.get("c", float("nan"))
    r2 = lotka.get("r_squared", float("nan"))
    # Generate fit line samples
    n_min, n_max = pts[0][0], pts[-1][0]
    fit_pts = []
    for n in np.linspace(n_min, n_max, 60):
        if n > 0:
            fit_pts.append((n, c * n ** (-alpha)))
    fit_rows = "\n".join(f"  {n:.3f}  {f:.4f}" for n, f in fit_pts if f > 0)

    body = f"""\\begin{{tikzpicture}}
\\begin{{axis}}[
  width=0.99\\linewidth, height=7cm,
  xmode=log, ymode=log, log basis x=10, log basis y=10,
  xlabel={{Publications per author $n$}},
  ylabel={{Number of authors $f(n)$}},
  legend pos=north east,
]
\\addplot+[only marks, mark=*, mark size=2pt, draw=blue!60!black, fill=blue!30]
  table[x index=0, y index=1] {{
{rows}
  }};
\\addlegendentry{{Observed}}
\\addplot+[smooth, thick, draw=red!70!black, mark=none]
  table[x index=0, y index=1] {{
{fit_rows}
  }};
\\addlegendentry{{Lotka fit, $\\alpha={alpha:.2f}$, $R^{2}={r2:.3f}$}}
\\end{{axis}}
\\end{{tikzpicture}}"""
    return _emit("F07_lotka_fit", body)


# ---------------------------------------------------------------------------
# F08 — Country production bubble.
# ---------------------------------------------------------------------------

def emit_country_bubble(top_countries: List[Tuple[str, int]], top_n: int = 20) -> Path:
    items = list(top_countries)[:top_n]
    if not items:
        body = "\\begin{tikzpicture}\\node{No data};\\end{tikzpicture}"
        return _emit("F08_country_bubble", body)
    items.sort(key=lambda x: -x[1])
    rows = "\n".join(
        f"  {i+1}  {c}  {{{_esc(name)}}}" for i, (name, c) in enumerate(items)
    )
    yticks = ",".join(str(i + 1) for i in range(len(items)))
    yticklabels = ",".join("{" + _esc(n) + "}" for n, _ in items)

    body = f"""\\begin{{tikzpicture}}
\\begin{{axis}}[
  width=0.99\\linewidth, height=10cm,
  xbar, bar width=4pt, enlarge y limits=0.03,
  ymin=0.5, ymax={len(items) + 0.5}, xmin=0,
  xlabel={{Documents (any-author affiliation)}},
  ytick={{{yticks}}}, yticklabels={{{yticklabels}}},
  ytick={{{yticks}}}, y dir=reverse,
  nodes near coords, every node near coord/.append style={{font=\\scriptsize}},
]
\\addplot+[fill=orange!70!black, draw=none]
  table[x index=1, y index=0] {{
    Y X
{rows}
  }};
\\end{{axis}}
\\end{{tikzpicture}}"""
    return _emit("F08_country_bubble", body)


# ---------------------------------------------------------------------------
# F09 — Country collaboration arc/chord (TikZ hand-positioned arc).
# ---------------------------------------------------------------------------

def emit_country_chord(affiliation: Dict[str, Any], top_countries_n: int = 12) -> Path:
    edges = affiliation.get("collaboration_edges", [])
    top = [c for c, _ in affiliation.get("top_countries", [])][:top_countries_n]
    top_set = set(top)
    edges = [e for e in edges if e["source"] in top_set and e["target"] in top_set]
    if not edges:
        body = "\\begin{tikzpicture}\\node{No collaboration edges};\\end{tikzpicture}"
        return _emit("F09_country_chord", body)

    n = len(top)
    # Position countries on a circle.
    placements = []
    for i, c in enumerate(top):
        angle = 90 - (360 * i / n)
        placements.append((c, angle))

    nodes = "\n".join(
        f"\\node[draw=black!50, fill=orange!15, rounded corners=2pt, font=\\scriptsize, "
        f"inner sep=2pt] ({_safe_id(c)}) at ({a}:4.2cm) {{{_esc(c)}}};"
        for c, a in placements
    )
    max_w = max(e["weight"] for e in edges)
    edges_lines = "\n".join(
        f"\\draw[gray!{40 + int(50 * e['weight'] / max_w)}, line width={0.3 + 1.5 * e['weight']/max_w:.2f}pt] "
        f"({_safe_id(e['source'])}.center) to[bend left=18] ({_safe_id(e['target'])}.center);"
        for e in edges
    )

    body = f"""\\begin{{tikzpicture}}[scale=1.0]
{nodes}
\\begin{{scope}}[on background layer]
{edges_lines}
\\end{{scope}}
\\node[anchor=south, font=\\scriptsize] at (0, -5.0) {{Edge weight $=$ co-authored documents (top {n} countries)}};
\\end{{tikzpicture}}"""
    return _emit("F09_country_chord", body)


def _safe_id(s: str) -> str:
    """LaTeX-safe TikZ node id."""
    return "n" + "".join(ch for ch in str(s) if ch.isalnum())[:24]


# ---------------------------------------------------------------------------
# F10 — Keyword co-occurrence network (top-N nodes).
# ---------------------------------------------------------------------------

def emit_keyword_network(keyword_network: Dict[str, Any], top_n: int = 40,
                         seed: int = 42) -> Path:
    nodes = sorted(keyword_network["nodes"], key=lambda n: -n["occurrences"])[:top_n]
    keep = {n["label"] for n in nodes}
    edges = [e for e in keyword_network["edges"]
             if e["source"] in keep and e["target"] in keep]

    G = nx.Graph()
    for n in nodes:
        G.add_node(n["label"], occurrences=n["occurrences"])
    for e in edges:
        G.add_edge(e["source"], e["target"], weight=e["weight"])

    # Spring layout, scaled to TikZ canvas.
    pos = nx.spring_layout(G, seed=seed, k=1.6, iterations=150)
    xs = [p[0] for p in pos.values()]
    ys = [p[1] for p in pos.values()]
    if not xs:
        return _emit("F10_keyword_network", "\\begin{tikzpicture}\\node{No data};\\end{tikzpicture}")
    xrange = max(max(xs) - min(xs), 0.001)
    yrange = max(max(ys) - min(ys), 0.001)
    SCALE_X = 6.5
    SCALE_Y = 5.5
    norm_pos = {k: ((v[0] - min(xs)) / xrange * SCALE_X - SCALE_X / 2,
                     (v[1] - min(ys)) / yrange * SCALE_Y - SCALE_Y / 2)
                for k, v in pos.items()}

    # Draw edges (background), then nodes labelled if occurrences high.
    max_occ = max(n["occurrences"] for n in nodes)
    max_w = max((e["weight"] for e in edges), default=1)

    edge_lines = []
    for u, v, data in G.edges(data=True):
        x1, y1 = norm_pos[u]
        x2, y2 = norm_pos[v]
        w = data.get("weight", 1)
        opacity = 0.15 + 0.6 * (w / max_w)
        lw = 0.15 + 1.0 * (w / max_w)
        edge_lines.append(f"\\draw[gray, line width={lw:.2f}pt, opacity={opacity:.2f}] "
                          f"({x1:.3f},{y1:.3f}) -- ({x2:.3f},{y2:.3f});")

    # Draw every node; then place labels with greedy collision-avoidance and a
    # radial outward offset so peripheral labels do not pile up on the dense core
    # (reviewer R2 minor #2). Labels are prioritised by occurrence then degree.
    deg = dict(G.degree())
    ranked = sorted(nodes, key=lambda n: (-n["occurrences"], -deg.get(n["label"], 0)))

    node_lines = []
    for n in nodes:
        x, y = norm_pos[n["label"]]
        size = 1.5 + 7.0 * math.sqrt(n["occurrences"] / max_occ)
        node_lines.append(
            f"\\filldraw[fill=blue!50!black, fill opacity=0.55, draw=blue!70!black, "
            f"line width=0.3pt] ({x:.3f},{y:.3f}) circle ({size:.2f}pt);"
        )

    cx = sum(p[0] for p in norm_pos.values()) / max(len(norm_pos), 1)
    cy = sum(p[1] for p in norm_pos.values()) / max(len(norm_pos), 1)
    MIN_LABEL_DIST = 0.60   # min separation between placed label anchors (cm)
    MAX_LABELS = 24
    placed = []
    label_lines = []
    for n in ranked:
        if len(placed) >= MAX_LABELS:
            break
        x, y = norm_pos[n["label"]]
        dx, dy = x - cx, y - cy
        r = math.hypot(dx, dy) or 1.0
        # Push peripheral labels further out than central ones.
        off = 0.10 + 0.12 * min(r / (SCALE_X / 2), 1.0)
        lx, ly = x + dx / r * off, y + dy / r * off
        if any(math.hypot(lx - px, ly - py) < MIN_LABEL_DIST for px, py in placed):
            continue
        placed.append((lx, ly))
        anchor = "south" if dy >= 0 else "north"
        label_lines.append(
            f"\\node[font=\\tiny, anchor={anchor}, fill=white, fill opacity=0.78, "
            f"text opacity=1, inner sep=0.5pt, rounded corners=0.5pt] "
            f"at ({lx:.3f},{ly:.3f}) {{{_esc(n['label'])}}};"
        )

    body = f"""\\begin{{tikzpicture}}[scale=1.0]
\\begin{{scope}}[on background layer]
{chr(10).join(edge_lines)}
\\end{{scope}}
{chr(10).join(node_lines)}
{chr(10).join(label_lines)}
\\end{{tikzpicture}}"""
    return _emit("F10_keyword_network", body)


# ---------------------------------------------------------------------------
# F11 — Thematic map (Callon centrality × density).
# ---------------------------------------------------------------------------

def emit_thematic_map(thematic: Dict[str, Any]) -> Path:
    clusters = thematic.get("clusters", [])
    if not clusters:
        return _emit("F11_thematic_map", "\\begin{tikzpicture}\\node{No clusters};\\end{tikzpicture}")
    cent_med = thematic.get("centrality_median", 0)
    dens_med = thematic.get("density_median", 0)
    max_n = max(c["n_nodes"] for c in clusters)

    rows = []
    labels = []
    for c in clusters:
        x = c["centrality"]
        y = c["density"]
        # Bubble size from sqrt(n_nodes) — visually proportional to cluster mass.
        size_pt = 4 + 28 * math.sqrt(c["n_nodes"] / max_n)
        label = c["top_keywords"][0][0] if c["top_keywords"] else f"C{c['cluster_id']}"
        rows.append((x, y, size_pt, label, c["quadrant"], c["n_nodes"]))
    quad_colour = {
        "motor": "red!70!black",
        "basic_transversal": "blue!70!black",
        "niche": "purple!70!black",
        "emerging_or_declining": "orange!70!black",
    }

    bubble_lines = []
    for x, y, sz, lbl, q, n_nodes in rows:
        c = quad_colour.get(q, "gray")
        bubble_lines.append(
            f"\\filldraw[fill={c}, fill opacity=0.45, draw={c}, line width=0.4pt] "
            f"(axis cs:{x:.2f},{y:.2f}) circle ({sz:.1f}pt);"
        )
        bubble_lines.append(
            f"\\node[font=\\tiny, anchor=center] at (axis cs:{x:.2f},{y:.2f}) "
            f"{{{_esc(lbl[:14])}}};"
        )

    cmax = max(c["centrality"] for c in clusters) * 1.1
    dmax = max(c["density"] for c in clusters) * 1.1

    body = f"""\\begin{{tikzpicture}}
\\begin{{axis}}[
  width=0.99\\linewidth, height=8cm,
  xlabel={{Centrality (inter-cluster link strength)}},
  ylabel={{Density (intra-cluster link strength / size)}},
  xmin=0, xmax={cmax:.2f}, ymin=0, ymax={dmax:.2f},
  axis lines=middle, axis line style={{->}},
  enlargelimits=false,
]
% Median split lines.
\\addplot[gray!50, dashed, no marks, line width=0.4pt] coordinates {{({cent_med:.2f}, 0) ({cent_med:.2f}, {dmax:.2f})}};
\\addplot[gray!50, dashed, no marks, line width=0.4pt] coordinates {{(0, {dens_med:.2f}) ({cmax:.2f}, {dens_med:.2f})}};
% Quadrant labels.
\\node[anchor=north east, font=\\scriptsize\\itshape, gray] at (axis cs:{cmax*0.99:.2f},{dmax*0.97:.2f}) {{Motor}};
\\node[anchor=north west, font=\\scriptsize\\itshape, gray] at (axis cs:{cmax*0.01:.2f},{dmax*0.97:.2f}) {{Niche}};
\\node[anchor=south east, font=\\scriptsize\\itshape, gray] at (axis cs:{cmax*0.99:.2f},{dmax*0.03:.2f}) {{Basic / transversal}};
\\node[anchor=south west, font=\\scriptsize\\itshape, gray] at (axis cs:{cmax*0.01:.2f},{dmax*0.03:.2f}) {{Emerging or declining}};
{chr(10).join(bubble_lines)}
\\end{{axis}}
\\end{{tikzpicture}}"""
    return _emit("F11_thematic_map", body)


# ---------------------------------------------------------------------------
# F12 — Three-field plot (Sources × Authors × Keywords).
# ---------------------------------------------------------------------------

def emit_three_field_plot(three: Dict[str, Any], max_per_axis: int = 8) -> Path:
    src = three.get("top_sources", [])[:max_per_axis]
    auth = three.get("top_authors", [])[:max_per_axis]
    kws = three.get("top_keywords", [])[:max_per_axis]
    sk = three.get("source_keyword_flows", [])
    ak = three.get("author_keyword_flows", [])

    if not (src and auth and kws):
        return _emit("F12_three_field", "\\begin{tikzpicture}\\node{No flows};\\end{tikzpicture}")

    # Position columns at x=0, 5, 10; y descends from top.
    H = 8.0
    def _ypos(i, n):
        return H - (i + 0.5) * H / n

    src_pos = {s: (0.0, _ypos(i, len(src))) for i, (s, _) in enumerate(src)}
    auth_pos = {a: (5.0, _ypos(i, len(auth))) for i, (a, _) in enumerate(auth)}
    kw_pos = {k: (10.0, _ypos(i, len(kws))) for i, (k, _) in enumerate(kws)}

    nodes_lines = []
    for s, c in src:
        x, y = src_pos[s]
        nodes_lines.append(
            f"\\node[draw=black!40, fill=blue!10, rounded corners=2pt, font=\\tiny, "
            f"inner sep=1.5pt, anchor=east, text width=3.5cm, align=right] "
            f"({_safe_id('S' + s)}) at ({x:.2f},{y:.2f}) {{{_esc(s[:48])} ({c})}};"
        )
    for a, c in auth:
        x, y = auth_pos[a]
        nodes_lines.append(
            f"\\node[draw=black!40, fill=teal!12, rounded corners=2pt, font=\\tiny, "
            f"inner sep=1.5pt, anchor=center, text width=2.6cm, align=center] "
            f"({_safe_id('A' + a)}) at ({x:.2f},{y:.2f}) {{{_esc(a[:32])} ({c})}};"
        )
    for k, c in kws:
        x, y = kw_pos[k]
        nodes_lines.append(
            f"\\node[draw=black!40, fill=orange!15, rounded corners=2pt, font=\\tiny, "
            f"inner sep=1.5pt, anchor=west, text width=3.5cm, align=left] "
            f"({_safe_id('K' + k)}) at ({x:.2f},{y:.2f}) {{{_esc(k[:48])} ({c})}};"
        )

    edge_lines = []
    max_w_sk = max((e["weight"] for e in sk), default=1)
    for e in sk[:25]:
        if e["source"] in src_pos and e["keyword"] in kw_pos:
            w = e["weight"]
            opa = 0.15 + 0.6 * (w / max_w_sk)
            edge_lines.append(
                f"\\draw[blue!60!black, line width={0.2 + 1.4 * w / max_w_sk:.2f}pt, "
                f"opacity={opa:.2f}] "
                f"({_safe_id('S' + e['source'])}.east) to[out=0,in=180] "
                f"({_safe_id('A' + auth[0][0])}.west);"  # routing through authors col
            )
    max_w_ak = max((e["weight"] for e in ak), default=1)
    for e in ak[:25]:
        if e["author"] in auth_pos and e["keyword"] in kw_pos:
            w = e["weight"]
            opa = 0.15 + 0.6 * (w / max_w_ak)
            edge_lines.append(
                f"\\draw[teal!70!black, line width={0.2 + 1.4 * w / max_w_ak:.2f}pt, "
                f"opacity={opa:.2f}] "
                f"({_safe_id('A' + e['author'])}.east) to[out=0,in=180] "
                f"({_safe_id('K' + e['keyword'])}.west);"
            )

    headers = (
        "\\node[anchor=south, font=\\scriptsize\\bfseries] at (0, 8.4) {Sources};"
        "\\node[anchor=south, font=\\scriptsize\\bfseries] at (5, 8.4) {Authors};"
        "\\node[anchor=south, font=\\scriptsize\\bfseries] at (10, 8.4) {Keywords};"
    )

    body = f"""\\begin{{tikzpicture}}[x=1cm, y=1cm]
{headers}
{chr(10).join(nodes_lines)}
\\begin{{scope}}[on background layer]
{chr(10).join(edge_lines)}
\\end{{scope}}
\\end{{tikzpicture}}"""
    return _emit("F12_three_field", body)


# ---------------------------------------------------------------------------
# F13 — Trend topics heatmap.
# ---------------------------------------------------------------------------

def emit_trend_topics_heatmap(trend: Dict[str, Any], top_n: int = 15) -> Path:
    fb = trend.get("frequency_by_year", {})
    years = fb.get("years", [])
    keywords = fb.get("keywords", [])[:top_n]
    matrix = fb.get("matrix", [])[:top_n]
    if not (years and keywords):
        return _emit("F13_trend_topics_heatmap", "\\begin{tikzpicture}\\node{No data};\\end{tikzpicture}")

    # Restrict to years 2008..2026 for legibility, dropping the old long tail.
    keep_idx = [i for i, y in enumerate(years) if y >= 2008]
    years_k = [years[i] for i in keep_idx]
    matrix_k = [[row[i] for i in keep_idx] for row in matrix]

    max_v = max((max(r) if r else 0) for r in matrix_k)
    rows_data = []
    for ki, kw in enumerate(keywords):
        for yi, y in enumerate(years_k):
            v = matrix_k[ki][yi]
            rows_data.append((y, ki, v))

    data_block = "\n".join(f"  {y} {ki} {v}" for y, ki, v in rows_data)
    yticklabels = ",".join("{" + _esc(k) + "}" for k in keywords)
    yticks = ",".join(str(i) for i in range(len(keywords)))

    body = f"""\\begin{{tikzpicture}}
\\begin{{axis}}[
  width=0.99\\linewidth, height=9cm,
  view={{0}}{{90}}, colormap/blackwhite, point meta min=0, point meta max={max_v},
  enlargelimits=false, xlabel={{Year}}, ylabel={{}},
  ytick={{{yticks}}}, yticklabels={{{yticklabels}}},
  ymin=-0.5, ymax={len(keywords) - 0.5},
  xmin={min(years_k)-0.5}, xmax={max(years_k)+0.5},
  colorbar, colorbar style={{width=0.3cm, font=\\tiny}},
]
\\addplot3[matrix plot*, point meta=explicit, mesh/cols={len(years_k)}]
  table[meta=z] {{
    x y z
{data_block}
  }};
\\end{{axis}}
\\end{{tikzpicture}}"""
    return _emit("F13_trend_topics_heatmap", body)


# ---------------------------------------------------------------------------
# F14 — Emergence index top-N.
# ---------------------------------------------------------------------------

def emit_emergence_top(trend: Dict[str, Any], top_n: int = 15) -> Path:
    items = list(trend.get("emergence", []))[:top_n][::-1]
    if not items:
        return _emit("F14_emergence_top", "\\begin{tikzpicture}\\node{No data};\\end{tikzpicture}")
    yticks = ",".join(str(i + 1) for i in range(len(items)))
    yticklabels = ",".join("{" + _esc(e["keyword"]) + "}" for e in items)
    rows = "\n".join(f"  {i+1}  {e['emergence_index']:.3f}" for i, e in enumerate(items))
    body = f"""\\begin{{tikzpicture}}
\\begin{{axis}}[
  width=0.99\\linewidth, height=8.5cm,
  xbar, bar width=5pt, enlarge y limits=0.04,
  ymin=0.5, ymax={len(items) + 0.5},
  xlabel={{Emergence index $(r-p)/\\max(p,1)$}},
  ytick={{{yticks}}}, yticklabels={{{yticklabels}}},
  nodes near coords, every node near coord/.append style={{font=\\scriptsize}},
]
\\addplot+[fill=red!60!black, draw=none]
  table[x index=1, y index=0] {{
    Y X
{rows}
  }};
\\end{{axis}}
\\end{{tikzpicture}}"""
    return _emit("F14_emergence_top", body)


# ---------------------------------------------------------------------------
# F15 — Sensitivity heatmap (γ × min-occ ARI).
# ---------------------------------------------------------------------------

def emit_sensitivity_heatmap(sensitivity: Dict[str, Any]) -> Path:
    ari = sensitivity.get("ari_vs_baseline_gamma", {}).get("ari", {})
    gammas = sorted(ari.keys(), key=float)
    if not gammas:
        return _emit("F15_sensitivity_heatmap", "\\begin{tikzpicture}\\node{No data};\\end{tikzpicture}")
    rows = "\n".join(f"  {g}  {ari[g]:.4f}" for g in gammas)
    cluster_counts = sensitivity.get("cluster_counts_by_gamma", {})

    annotation = "\n".join(
        f"\\node[font=\\tiny] at (axis cs:{float(g)},{ari[g]:.3f}) [anchor=south] "
        f"{{{cluster_counts.get(g, '?')} cl.}};"
        for g in gammas
    )

    body = f"""\\begin{{tikzpicture}}
\\begin{{axis}}[
  width=0.99\\linewidth, height=6cm,
  xlabel={{Resolution $\\gamma$}},
  ylabel={{ARI vs.\\ baseline}},
  xmin=0.4, xmax=1.6, ymin=0, ymax=1.05,
  ymajorgrids,
]
\\addplot+[smooth, mark=*, mark size=2pt, draw=blue!60!black]
  table[x index=0, y index=1] {{
    g ari
{rows}
  }};
{annotation}
\\addplot[red, dashed] coordinates {{(0.4, 1) (1.6, 1)}};
\\end{{axis}}
\\end{{tikzpicture}}"""
    return _emit("F15_sensitivity_heatmap", body)


# ---------------------------------------------------------------------------
# F16 — Temporal coupling 3-panel.
# ---------------------------------------------------------------------------

def emit_temporal_coupling(coupling: Dict[str, Any]) -> Path:
    eras = coupling.get("eras", {})
    labels = list(eras.keys())
    if not labels:
        return _emit("F16_temporal_coupling", "\\begin{tikzpicture}\\node{No data};\\end{tikzpicture}")
    panels = []
    for i, label in enumerate(labels):
        info = eras[label]
        n_docs = info.get("n_docs", 0)
        n_edges = info.get("n_coupling_edges", 0)
        density = info.get("density", 0)
        panels.append(
            f"\\node[draw=black!40, rounded corners=3pt, fill=blue!5, inner sep=4pt, "
            f"text width=4.4cm, align=center] (P{i}) at ({i * 5}, 0) "
            f"{{{{\\bfseries {_esc(label)}}}\\\\[2pt]"
            f"\\scriptsize $n_{{\\text{{docs}}}}={n_docs}$ \\quad "
            f"$|E|={n_edges}$ \\\\[1pt] density $={density:.4f}$}};"
        )
    body = f"""\\begin{{tikzpicture}}
{chr(10).join(panels)}
\\node[anchor=south, font=\\scriptsize\\itshape, gray] at (5, 1.2) {{Bibliographic-coupling structure stratified by era — see Table~\\ref{{tab:era-shifts}} for Kendall's $\\tau$ between consecutive eras}};
\\end{{tikzpicture}}"""
    return _emit("F16_temporal_coupling", body)


# ---------------------------------------------------------------------------
# F02 already produced via F01's secondary axis — emit a separate compact one.
# ---------------------------------------------------------------------------

def emit_completeness_only(completeness: Dict[str, Any], by_year: pd.DataFrame) -> Path:
    df = by_year.sort_values("Year").reset_index(drop=True)
    cum = df["count"].cumsum().tolist()
    rows = "\n".join(f"  {int(y)}  {int(c)}" for y, c in zip(df["Year"], cum))
    sat = completeness.get("saturation_ratio", float("nan"))
    body = f"""\\begin{{tikzpicture}}
\\begin{{axis}}[
  width=0.99\\linewidth, height=6cm,
  xlabel={{Year}}, ylabel={{Cumulative publications}},
  legend pos=south east, ymajorgrids,
]
\\addplot+[only marks, mark=*, mark size=1.5pt, draw=blue!60!black]
  table[x index=0, y index=1] {{
{rows}
  }};
\\addlegendentry{{Observed}}
\\node[anchor=north west, font=\\scriptsize, draw=black!30, inner sep=2pt, align=left]
  at (axis cs:{int(df['Year'].min())},{max(cum)*0.97:.0f})
  {{Linear $R^{2}={completeness['linear_r2']:.3f}$\\\\
    Exp.\\ $R^{2}={completeness['exponential_r2']:.3f}$\\\\
    Gompertz $R^{2}={completeness['gompertz_r2']:.3f}$\\\\
    Bi-logistic $R^{2}={completeness.get('bilogistic_r2', float('nan')):.3f}$\\\\
    Best model (AIC): {_esc(str(completeness.get('best_model', 'n/a')))}\\\\
    Gompertz saturation $={sat:.3f}$}};
\\end{{axis}}
\\end{{tikzpicture}}"""
    return _emit("F02_completeness", body)


# ---------------------------------------------------------------------------
# Driver — load JSON outputs and emit all figures.
# ---------------------------------------------------------------------------

def main() -> None:
    print("Generating TikZ figures into", FIGDIR)

    # Load all artefacts.
    try:
        scopus_csv = next(p for p in (ROOT / "data").glob("scopus_export*.csv")
                          if "debiased" in p.name.lower())
    except StopIteration:
        scopus_csv = next((ROOT / "data").glob("scopus_export*.csv"))
    df = pd.read_csv(scopus_csv, encoding="utf-8-sig")
    by_year = df.groupby("Year").size().reset_index(name="count")

    affiliation = json.loads((PROCESSED / "affiliation_matrix.json").read_text())
    sensitivity = json.loads((PROCESSED / "sensitivity_matrix.json").read_text())
    coupling = json.loads((PROCESSED / "coupling_eras.json").read_text())
    bradford = json.loads((PROCESSED / "bradford.json").read_text())
    lotka = json.loads((PROCESSED / "lotka.json").read_text())
    thematic = json.loads((PROCESSED / "thematic_map.json").read_text())
    trend = json.loads((PROCESSED / "trend_topics.json").read_text())
    three = json.loads((PROCESSED / "three_field.json").read_text())
    keyword_network = json.loads((PROCESSED / "keyword_network.json").read_text())

    # Recompute completeness on demand (cheap, ~1s).
    from bibliometric_analyzer import ScopusAnalyzer
    completeness = ScopusAnalyzer(str(scopus_csv)).compute_field_completeness_score()

    # Top author keywords from the keyword_network or recomputed.
    kw_counts: List[Tuple[str, int]] = sorted(
        ((n["label"], n["occurrences"]) for n in keyword_network["nodes"]),
        key=lambda x: -x[1],
    )

    print(emit_publication_timeline(by_year, completeness))
    print(emit_completeness_only(completeness, by_year))
    print(emit_top_keywords(kw_counts))
    print(emit_top_sources_bradford(bradford))
    print(emit_bradford_curve(bradford))
    print(emit_top_authors(lotka.get("top_authors", [])))
    print(emit_lotka_fit(lotka))
    print(emit_country_bubble(affiliation.get("top_countries", [])))
    print(emit_country_chord(affiliation))
    print(emit_keyword_network(keyword_network))
    print(emit_thematic_map(thematic))
    print(emit_three_field_plot(three))
    print(emit_trend_topics_heatmap(trend))
    print(emit_emergence_top(trend))
    print(emit_sensitivity_heatmap(sensitivity))
    print(emit_temporal_coupling(coupling))


if __name__ == "__main__":
    main()
